baseURL = "https://willgreenberg.github.io/blog/"
languageCode = "en-us"
title = "Digestible"
theme = "hemingway2"
publishDir = "docs"
description = "Flicking the light switch on CS"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/willgreenberg"
fa_icon = "fa-github"
